### ISSUE TITLE
Notifications error message

### ISSUE THREAD

**Issue by AfricaSaga** [devgianlu/Aria2App#100]
I have just started using the application for remote control of a local server aria2c setup.
It works well, except for notifications:
Two messages appear on the notification panel, one refers to a notification service and cannot be removed, the other one says notifications won't work without websockets (?).
Please see attached screenshot.

Expected behavior: no permanent notifications service panel, and actual notifications for aria2c related events.

Thank you.

Screenshot:
(https://user-images.githubusercontent.com/63705761/81392423-8da61000-9116-11ea-8f01-98acda010c74.jpg)

**Comment by devgianlu** [comment]
For the error message: notifications with HTTP as a connection method is not possible, you need to switch to WebSocket.

For the permanent notification: it was once available an option to disable the foreground service, but it wasn't working reliably so I've removed it.
