### ISSUE TITLE
Default trackers add to BT

### ISSUE THREAD

**Issue by WhiCCX0** [devgianlu/Aria2App#104]
Here is an aria2 high-quality bt Tracker list collection on  [Trackerlist](https://trackerslist.com/) 
Can set [Aria Trackerlist](https://trackerslist.com/best_aria2.txt)  to the default tracker list when adding a new download task in the option.

**Comment by devgianlu** [comment]
I suppose I can expand the automatic trackers feature to allow using custom sources.

Will work on it.
