### ISSUE TITLE
Issues in ProgressBar

### ISSUE THREAD

**Issue by john2020star** [devgianlu/Aria2App#106]
Hi,

I found there is a compatibility issues in the progress bar of activity_loading.xml

`            <ProgressBar
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_horizontal"
                android:layout_marginTop="8dp"
                android:indeterminateTint="@color/colorSecondary" />`

You only set indeterminateTint without indeterminateTintMode, causing the color in ProgressBar inconsistent in API Level 21 and 22. Add android:indeterminateTintMode="src_in" will fix this issue.

**Comment by devgianlu** [comment]
Thank you.
