### ISSUE TITLE
No f-droid update 5.8.0

### ISSUE THREAD

**Issue by Scripterr** [devgianlu/Aria2App#107]
There is no update for version 5.8.0 on f-droid??
20 days has passed since the version 5.8.0 release, do you know why there is no f-droid update to the app.
Thanks

**Comment by devgianlu** [comment]
I have no idea why it's not published on F-Droid. The [metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.gianlu.aria2app.yml) is updated, but the [builds](https://f-droid.org/wiki/page/com.gianlu.aria2app/lastbuild_210) are failing before even starting. 

Guess I'll have to open another issue that will take months to resolve: https://gitlab.com/fdroid/fdroiddata/-/issues/2121

**Comment by devgianlu** [comment]
Seems to be all their fault, they are fixing it.

**Comment by devgianlu** [comment]
5.8.0 is now available.
