### ISSUE TITLE
[Duplicate] Download to external storage

### ISSUE THREAD

**Issue by Albnu14** [devgianlu/Aria2App#115]
How can I download to my external storage?
If I set the path with the "dir" option it ends with an error
If I set the download path from settings of directdownload the path doesn't change
Is there a way to download to external storage?

**Comment by devgianlu** [comment]
See https://github.com/devgianlu/Aria2Android/issues/19 and the [wiki](https://github.com/devgianlu/Aria2App/wiki/Issues-with-SD-card).

**Comment by Albnu14** [comment]
Thanks I just checked them,
I will this issue because it seems to be a duplicate.
