### ISSUE TITLE
Aria2 is a command line tool, not a server.

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [devgianlu/Aria2App#12]
It's unclear howto start server, moreover unable to open https://gianlu.xyz/documents/Aria2App/create-profile/ just blank page shown

**Comment by devgianlu** [comment]
I should update the link: http://gianlu.xyz/projects/Aria2App/documents/create-profile/

**Comment by devgianlu** [comment]
fea4d4d600074992d100bcf2c941be5a41aeb4ac
