### ISSUE TITLE
Detect download links in browser

### ISSUE THREAD

**Issue by arhayati** [devgianlu/Aria2App#137]
Some download managers (such as ADM) can detect links of videos or songs or other files in browser. ADM has a built-in browser that you can use to download videos on sites that don't provide download option. It would be awesome if Aria2App could add such feature.

**Comment by devgianlu** [comment]
This feature is already available, it doesn't work perfectly everytime, but you can always share a link with Aria2App or use the built-in WebView that allows to intercept any download or network request.

**Comment by arhayati** [comment]
I didn't know that. Thanks.

Also, if therr were an option to show possible download links in a table so we could select links and see the file format of files, it would be super.

**Comment by devgianlu** [comment]
You can see all possible download links by pressing the download button in the top right corner (of the WebView screen) and then pressing "previous".
