### ISSUE TITLE
[bug] A display issue

### ISSUE THREAD

**Issue by franklinbill** [devgianlu/Aria2App#140]
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the red box, "user" in the component is not displayed completely. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
App version is 5.9.5, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
<img width="554" alt="bug-aria2app" src="https://user-images.githubusercontent.com/18572115/103147182-ae96a080-478d-11eb-9cce-5ee64e7c3b43.png">

**Comment by devgianlu** [comment]
Clearly an issue here, but I don't really know how I might fix it without changing the way the selection is made.

**Comment by devgianlu** [comment]
I think this is a bit of an edge case and the text isn't completely hidden so one might understand what the button is intended for anyway.
