### ISSUE TITLE
Fails to resolve DNS query when using a VPN

### ISSUE THREAD

**Issue by proletarius101** [devgianlu/Aria2App#142]
When a VPN is enabled, Aria 2 fails to resolve DNS queries since its default DNS server is 192.168.3.1 which is not used by the VPN. Somehow that setting can't be changed. So no workaround for now.

**Comment by devgianlu** [comment]
I think you can use this option: https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-async-dns-server

**Comment by proletarius101** [comment]
Well, exactly. When I tweak this and tap apply, it doesn't take any effect. You may even see the 192.168.3.1 comes back when you open the edit popup again.

**Comment by devgianlu** [comment]
Are you using the InApp Downloader or a remote server? If you are using the InAppDownloader I suggest adding the option by long pressing the profile and editing the custom options. Have a look at the log as it may display errors.

**Comment by proletarius101** [comment]
The inapp one. 
Sorry but long pressing the profile doesn't lead me to the options, but the log files?
I edited the global options and it wasn't changed after I opened the panel again. But somehow it works now (maybe it needs an app restart?). The custom async dns option for a specific job is empty though.
Anyway, I believe it will be good to have some automation here ;)

**Comment by devgianlu** [comment]
Options set from the main UI are temporary and reset upon restart, that's the default behaviour of aria2.

You are seeing only the logs because you need to stop the service first. After stopping you'll be able to see a button for custom options. These options are permanent and persisteted upon restart.

**Comment by proletarius101** [comment]
Got it. I see I've somehow set the permanent option. Thanks 😀
