### ISSUE TITLE
Update Navigation Drawer design

### ISSUE THREAD

**Issue by CaesarW** [devgianlu/Aria2App#15]
Dear developer!

Super glad to hear the app is now open source, which makes it easier to contribute and provide feedback.

So, little suggestions here. 
1. It's better if you can make the side bar fonts bold (see screenshot below). 
1. Sometimes when adding URLs the app may stuck at "Gathering information". And I need to force quit the app in order to add the link again. Sorry I can't provide log here.  

![Screenshot](https://i.imgur.com/sJzhgSU.jpg)

Thanks in advance!

**Comment by CaesarW** [comment]
Issue edited. One more feedback added.

**Comment by devgianlu** [comment]
![screenshot_1542639105](https://user-images.githubusercontent.com/14827249/48714586-491d7080-ec13-11e8-8df4-39aa0d04c823.png)

**Comment by devgianlu** [comment]
I've created #16 for the other issue.
