### ISSUE TITLE
[R] Custom number connections

### ISSUE THREAD

**Issue by mizzunet** [devgianlu/Aria2App#153]
Is it possible to use a specific number of connections? Is it even possible with aria2c?

**Comment by devgianlu** [comment]
Have a look at [max-connection-per-server](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-x) and [split](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-s).

**Comment by mizzunet** [comment]
> Have a look at [max-connection-per-server](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-x) and [split](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-s).

Nice! But Aria2App doesn't have functionality to use different number, does it?

**Comment by devgianlu** [comment]
You can set those options for the InApp-Downloader.

**Comment by mizzunet** [comment]
> You can set those options for the InApp-Downloader.

![Screenshot_20210215-200138](https://user-images.githubusercontent.com/10193999/107958858-f98ea080-6fe5-11eb-826e-3fa6e9a24f64.png)
Yeah, found it. Thanks

**Comment by devgianlu** [comment]
Actually, setting it there will make it temporary. You need to press and hold on the In-App Downloader profile and add a custom option.

**Comment by mizzunet** [comment]
> Actually, setting it there will make it temporary. You need to press and hold on the In-App Downloader profile and add a custom option.

I see, thanks
