### ISSUE TITLE
[R] Tap result to open

### ISSUE THREAD

**Issue by mizzunet** [devgianlu/Aria2App#154]
Open the downloaded by tapping the result

**Comment by devgianlu** [comment]
Could you explain a bit better?

**Comment by mizzunet** [comment]
> Could you explain a bit better?

![Screenshot_20210215-195754_1](https://user-imagHere'sthubusercontent.com/10193999/107958525-7a996800-6fe5-11eb-9bfd-60616842ccfb.png)
Here's a downloaded file, the file should open when we tap on it, currently it shows more info when we tap on it

**Comment by devgianlu** [comment]
That's the intended behavior.

**Comment by mizzunet** [comment]
> That's the intended behavior.

Yeah, but is it worth if it opened or at least an Open button near it?

**Comment by devgianlu** [comment]
Added!

**Comment by mizzunet** [comment]
Thanks👌
