### ISSUE TITLE
Option of auto paste clipboard to new task or webview

### ISSUE THREAD

**Issue by leungzw** [devgianlu/Aria2App#156]
I think when people want to download something with android phone, there's download/magnet link in the clipboard,
It would be help if the link can be pasted to the URL automatically.
I remember the there was the function in a old version, but no longer available after update.
Will the function, or option can be seen in the future?
Thanks much for great job.

**Comment by devgianlu** [comment]
This feature is still available in newer version. It will auto paste the URL when you open the add URI screen.

**Comment by leungzw** [comment]
OK, finally I found the reason was my phone prohibited apps accessing from clipboard.
