### ISSUE TITLE
Night/Dark Mode related UI issue

### ISSUE THREAD

**Issue by SumatraPeter** [devgianlu/Aria2App#159]
When Night/Dark Mode is enabled, the 3 dots menu at the top right (with the Sort/Pause/Resume/Purge options) becomes black text on almost-black background. With a low brightness setting nothing can be seen, and even on high brightness it's quite hard to see.

An inverted color scheme of white text on almost-black background for that menu (and any others similarly affected) would obviously be the way to go.

**Comment by devgianlu** [comment]
Can you attach a screenshot? It looks fine on my test devices going from Android 6 to 10.

**Comment by SumatraPeter** [comment]
Sure, here you go:

![Screenshot_2021-02-24](https://user-images.githubusercontent.com/15380332/108955474-3fa5cd00-7694-11eb-8092-66d14310752a.jpg)

This is on Android 5.0.1 BTW (haven't found a newer ROM for this Lenovo Yoga Tab 2 Pro).

**Comment by devgianlu** [comment]
That seems an issue with the Material Design library because I am not toggling anything in that regards.

**Comment by SumatraPeter** [comment]
Well, since no bug fix is ever going to make it to old Android versions, I do hope you can at least work around it.

**Comment by devgianlu** [comment]
It believe the issue wasn't there on older versions, hopefully it is fixed with the latest one.

**Comment by SumatraPeter** [comment]
By '"latest one " do you mean 5.9.6, or the next version 5.9.7?

BTW, I just realized I'm still on 5.9.5 - any idea how long it takes after release here to make it to the official F-Droid repository?

**Comment by devgianlu** [comment]
It can be 2 days or one week. Very often they have issues when the deployment and take a month to fix it.

**Comment by SumatraPeter** [comment]
5.9.5 from F-Droid was the first version of this app I used, and now I'm on 5.9.6 via APK from here.

**Comment by devgianlu** [comment]
I've now enforced the menu item color on Android 5.0.1, should be fixed. Please reopen if the issue persists.

**Comment by SumatraPeter** [comment]
Thanks, I'll test as soon as the APK for 5.9.7 is made available here.
