### ISSUE TITLE
Cannot add URL download

### ISSUE THREAD

**Issue by devgianlu** [devgianlu/Aria2App#16]
@CaesarW

>Sometimes when adding URLs the app may stuck at "Gathering information". And I need to force quit the app in order to add the link again. Sorry I can't provide log here.

**Comment by devgianlu** [comment]
@CaesarW Without logs I can't do much. Are you able to provide them? Send me an email from the app after reproducing the issue.

**Comment by CaesarW** [comment]
@devgianlu I've noticed the "log" section in the app preference but I can't export them to files. Can I provide screenshots and the logcat file scrubbed by other app?

**Comment by devgianlu** [comment]
I would prefer the email, but that should also work. You should be able to see red stuff, click on it to expand it and take a screenshot of that.

**Comment by CaesarW** [comment]
Screenshots:
![Screenshot 1](https://i.imgur.com/gj7zPrW.png)
![Screenshot 2](https://i.imgur.com/Vqzx3w6.png)
![Screenshot 3](https://i.imgur.com/BBM6XWm.png)
![Screenshot 4](https://i.imgur.com/sgD5ukp.png)
![Screenshot 5](https://i.imgur.com/birUGza.png)
![Screenshot 6](https://i.imgur.com/MrR1DO7.png)
![Screenshot 7](https://i.imgur.com/FJqNI4c.png)
![Screenshot 8](https://i.imgur.com/0UCnOif.png)
![Screenshot 9](https://i.imgur.com/IxQnMLM.png)
![Screenshot 10](https://i.imgur.com/MLK6JlW.png)

These screenshots are taken from different ERRORs.

Thanks

**Comment by devgianlu** [comment]
Did you reproduce the issue before checking the logs? These errors don't effect the issue you are experiencing, in fact, they aren't even an issue.

**Comment by CaesarW** [comment]
Yes I took these screenshots after reproduction.

**Comment by devgianlu** [comment]
There's nothing really obvious, I'll investigate this further.

**Comment by devgianlu** [comment]
Closed after #23
