### ISSUE TITLE
SSL/TLS handshake failed

### ISSUE THREAD

**Issue by buergi** [devgianlu/Aria2App#163]
I get an SSL/TLS handshake failed error when trying to download e.g. https://ftp.gwdg.de/pub/misc/openstreetmap/openandromaps/mapsV4/europe/Malta.zip in the current version 1.35.0.

Guess this is a problem of Aria2 itself, as I have the same problem also with the aria2c version which can be installed via termux.
e.g.

    aria2c --log - --check-certificate https://ftp.gwdg.de/pub/misc/openstreetmap/openandromaps/mapsV4/europe/Malta.zip

fails with error `SSL/TLS handshake failure: protocol error`

However, with aria2c on my computer (Archlinux) it works perfectly, so i'm not sure if it is not a problem of the aria2c builds, which would make it a problem indirectly caused by Aria2App. Even when explicitly specifying the identical trust chain used on my computer it does not work

    aria2c --ca-certificate=/sdcard/ca-certificates.crt --check-certificate https://ftp.gwdg.de/pub/misc/openstreetmap/openandromaps/mapsV4/europe/Malta.zip

Loading the same file with any Browser on Android or with curl or wget on termux does not throw any certificate errors.

The host has valid certificates, however the [SSL Server Test](https://www.ssllabs.com/ssltest/analyze.html?d=ftp.gwdg.de&s=134.76.12.6) notes some `Server sent fatal alert: handshake_failure` as well.

I'm not sure what the problem is...

**Comment by devgianlu** [comment]
No idea what's happening either. Possibly related to https://github.com/aria2/aria2/issues/1494?

**Comment by laggardkernel** [comment]
My assumption is the integration of `openssl` of `aria2` has some problem, it fails handshaking with some certs (It fails on my self signed cert). The one on your archlinux works well is because that is built with `gnutls`. For the time being, just stick with `gnutls` when building aria2.
