### ISSUE TITLE
WebView does not auto-upgrade to HTTPS

### ISSUE THREAD

**Issue by V3YNjKbFGLSQ0FzpOu1s** [devgianlu/Aria2App#165]
Hi, it seems that the app connects to whatever you type in the Go to field. Implementing a feature to auto-upgrade HTTP to HTTPS could make the app more secure.
![2021-03-12_17-35](https://user-images.githubusercontent.com/69808482/110954481-72142300-8340-11eb-9608-28a9ea058dec.png)

**Comment by devgianlu** [comment]
I believe the WebView implementation should do this.

**Comment by devgianlu** [comment]
This is WebView implementation related. Cannot do much about it because we cannot assume that an HTTPS version of the website is available.
