### ISSUE TITLE
Qrcode support

### ISSUE THREAD

**Issue by Louson** [devgianlu/Aria2App#170]
It would be nice to add link by qrcode. In my situation, I'd like a webview on a page after scan. What do you think ?

**Comment by devgianlu** [comment]
I think it's a bit overkill to have a qr code reader inside the app. Most devices these days have readers built inside the camera app.

**Comment by devgianlu** [comment]
It depends on the app, but you can usually get to Aria2Aapp by using the share button.

**Comment by Louson** [comment]
Wow that's true. Sorry, I had only tried the open with option. Thanks for this great app anyway !
