### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by Kita2345** [devgianlu/Aria2App#195]
Download error from https://nationsglory.fr/download
![Screenshot_2021-08-09-14-53-49-87_f3595b19c7910ba157f01b460eb2e7b5](https://user-images.githubusercontent.com/87817690/128674990-a12a7852-6bd1-4e2b-8525-eb62607fa287.jpg)

**Comment by devgianlu** [comment]
This is unrelated to the app, you may want to open an issue on [aria2](https://github.com/aria2/aria2), but that just seems a generic HTTP error. The website is probably using some protection and detecting a non-browser client.
