### ISSUE TITLE
sorry but i cannot found an answer by google - when connecting from another phone to this in-app downloader, unauthenticated request was successful, but authenticated request failed: ut "1824: xxx.ariaexception: unauthorized" ,

### ISSUE THREAD

**Issue by frankniu139** [devgianlu/Aria2App#196]
Hi, 
Hope this won't bother you too much. I wish I could get some answer on internet but no luck. You may check the following screenshot:

I ran in-app downloader servie on a phone, and on that phone itself i can connect to it successfully (just click the in app service), and can download torrent normally.
However when I try to connect to this in app downloader from another phone, i got following "test" result when adding a profile.

unauthenticated request was successful, but authenticated request failed: ut "1824: xxx.ariaexception: unauthorized. Your token or username and password may be wrong". 
However I checked on the server side in-app downloader, rpc-password and rpc-secret are both not set/empty. 
port is default 7186 so the unauthenticated request was successful.

If you could take time to give some hint that'll be great. Thank you.

![image](https://user-images.githubusercontent.com/37818321/129506167-bb00e897-9fe1-464a-81eb-adf6853e862d.png)

**Comment by devgianlu** [comment]
Both the port and secret are randomised. Please check in the in-app downloader configuration what their values are. Example:
![Screenshot_20210816-091905_Aria2App.png](https://user-images.githubusercontent.com/14827249/129525959-2fb711e6-e0d4-4b08-8f09-4f5cd5a4bb6a.png)

**Comment by frankniu139** [comment]
Wonderful. I got it.  Thank you so much. In addition, this is a so nice app!
