### ISSUE TITLE
Website non-text content not rendering

### ISSUE THREAD

**Issue by Kita2345** [devgianlu/Aria2App#201]
On this page: https://money.cnn.com/data/fear-and-greed

None of the charts show up
![Screenshot_2021-09-09-05-31-58-69_f3595b19c7910ba157f01b460eb2e7b5](https://user-images.githubusercontent.com/87817690/132594560-051111b7-1b0c-474d-bb9c-5037db2a8086.jpg)

**Comment by devgianlu** [comment]
I am sorry, but things that happen inside the webview are out of my control and most likely a bug in the underlying engine.
