### ISSUE TITLE
Open file button is share button

### ISSUE THREAD

**Issue by rollingmoai** [devgianlu/Aria2App#208]
This has been bugging me for many months (ever since I installed the app):

![image](https://user-images.githubusercontent.com/75471378/140669858-3c345ad6-f20c-44aa-8e93-2a444b55ff23.png)
![image](https://user-images.githubusercontent.com/75471378/140669864-d0d6d02e-4536-4b28-b529-446615995ada.png)

**Comment by devgianlu** [comment]
The app uses the [ACTION_VIEW](https://developer.android.com/reference/android/content/Intent#ACTION_VIEW) action which is the most appropriate for this. Not sure why your phone decided to handle it that way.
