### ISSUE TITLE
wrong file extension

### ISSUE THREAD

**Issue by Kita2345** [devgianlu/Aria2App#215]
Downloaded not in .png but in .php file extension.

Link
https://www.meteo.pl/um/metco/mgram_pict.php?ntype=0u&row=411&col=207&lang=pl

![Screenshot_2021-12-11-21-34-25](https://user-images.githubusercontent.com/87817690/145680372-6848a4eb-eae3-4a24-bdfb-db43bc4254f6.jpg)

**Comment by devgianlu** [comment]
This is definitely an issue with https://github.com/aria2/aria2.
