### ISSUE TITLE
Allow more than 5 links in add URI option.

### ISSUE THREAD

**Issue by Pravinsp107** [devgianlu/Aria2App#224]
The add URI option allows to enter links more than 5, but while downloading it takes only 5 links to download. Kindly allow all the added links for downloading. And kindly add the edit link option also while downloading itself.

**Comment by devgianlu** [comment]
You can modify the max concurrent downloads option to have more downloads going at once. Also, it is not possible to modify the download URL of a file while it is downloading. These are aria2 limitations.
