### ISSUE TITLE
ouput path can't be changed

### ISSUE THREAD

**Issue by FX9590** [devgianlu/Aria2App#226]
Default output path is "/". App log shows can't write at read-only file system.
I've tried to set "output path" to "/storage/emulated/0/Download/Aria2" in "In-app downloader configuration", but it still shows "/".
add a "dir" variable in "custom option" was also has been done, but still don't work.
In info of a bt task, "destinations dirextory" is "/storage/emulated/0/Download/Aria2" that i set, but of another https task, it is "/".
by the way, there is no file in "/storage/emulated/0/Download/Aria2".
there's anything wrong with my operation?
It'a Android 12 device.

**Comment by xicobiu** [comment]
Same issue

**Comment by devgianlu** [comment]
See https://github.com/devgianlu/Aria2App/wiki/Issues-with-SD-card and https://github.com/devgianlu/Aria2Android/issues/19
