### ISSUE TITLE
Reconsider analytics and telemetry

### ISSUE THREAD

**Issue by pritkr** [devgianlu/Aria2App#232]
The app has currently three tracker libraries to my knowledge
- Google Admob
- Google Crashlytics
- Google firebase analytics

Not only are these tracker libraries are not open source but also invasive to user privacy. I am not against removal of all analytics like crash reporting. But I don't like the fact that I was using this app thinking since it was open source it cared for user privacy. I also don't like that data is going to google and all data is uniquely identifiable. [[1](https://support.google.com/firebase/answer/6318039?hl=en)]
Clearly a disclosure of data collection and opt-in should've been given when the app is opened for first time.[[1](https://firebase.google.com/policies/analytics#:~:text=You%20are%20required%20to%20notify%20your%20App%20Users%20by%20disclosing%20the%20following%20information%3A)][[2](https://stackoverflow.com/q/54084979)]. Please consider removing all telemetry or replacing it with open source or self-hosted analytics. A separate build without tracker for f-droid can also be created.
I'm thankful to you for creating this app. Please fix this.

**Comment by devgianlu** [comment]
A FOSS build is already available: https://github.com/devgianlu/Aria2App/blob/e217b827c9d7c86066b7a2a68ae6a51d2d8c79e6/app/build.gradle#L53
