### ISSUE TITLE
It shows progress at 100% while not finished

### ISSUE THREAD

**Issue by libook** [devgianlu/Aria2App#235]
This is a very nice App. Thanks for your work.

BT downloading is always hard at the end.
Sometimes the task info showed it was in 100% progress. But some files in this task were in 99% progress.
Of course, the task was still running. It seemed just like a view problem.

It didn't affect the use. But it would be good that it could be fixed.

**Comment by devgianlu** [comment]
I think this is just a rounding issue either in Aria2App or aria2.

**Comment by libook** [comment]
> I think this is just a rounding issue either in Aria2App or aria2.

Yes, it could be.

I don't know much about Java. Sometimes I thought it would be better to use mechanisms like Math.floor(). But it may also cause "0%" output while there actually was more than 0% progress.

Hmmm, what an interesting problem.
