### ISSUE TITLE
F-droid version stays at 5.9.9

### ISSUE THREAD

**Issue by AsimovGod** [devgianlu/Aria2App#237]
The f-droid version stays at 5.9.9, which has huge problems on Android. Will you continue to support compiling f-droid version.

**Comment by devgianlu** [comment]
I've never stopped supporting it, not sure what happened on their side.

**Comment by AsimovGod** [comment]
> I've never stopped supporting it, not sure what happened on their side.

Could you please check the process of fdroid? I'm not familiar with it.

**Comment by AsimovGod** [comment]
@devgianlu  I have submitted a new merger issue. I don't know whether it will be effective, but I did it in another project before.
<https://gitlab.com/fdroid/rfp/-/issues/2152>

**Comment by AsimovGod** [comment]
It seems that many mistakes have been made
