### ISSUE TITLE
global speed and full file size

### ISSUE THREAD

**Issue by wxg1015** [devgianlu/Aria2App#253]
Two suggestions, the first one is to increase the global upload and download speed display.  Added display of full file size in second torrent info

**Comment by wxg1015** [comment]
Oh, right.  It would be even better if it could support the selection of all tasks and the batch copying of magnetic links.  Just like ariang.

**Comment by devgianlu** [comment]
>  It would be even better if it could support the selection of all tasks
 
 This is already covered by #211.
 
Not sure what you mean by "batch copying of magnetic links", you can already add multiple magnetic links at once. Also the full file size of torrent downloads is already present.
