### ISSUE TITLE
Pass cookies from webview to aria2

### ISSUE THREAD

**Issue by abskmj** [devgianlu/Aria2App#255]
First of all, I would like to thank you for such a great app. I have been using it for a year now and it is outstanding.

I trying to download a large file (around 50GB) that is shared on google drive. I'm able to login into google and access the file details webpage. When I click on the download button, the web view also detects the file and adds it as a download to aria2. But, aria2 downloads just a webpage instead of the file. 

It seems the access to the file was denied to aria2 as there are no cookies attached in the download request. Passing the cookies from the web view to the aria2 would solve this issue.

This feature would allow any downloads with access based on cookies. I would really appreciate it if this is added.

**Comment by devgianlu** [comment]
This functionality is already present actually: all request headers used are passed to aria2. There could be another issue that interfeers with that, perhaps Google Drive thinks someting fishy is going on.
