### ISSUE TITLE
Permission denied in Android 13

### ISSUE THREAD

**Issue by hm-tamim** [devgianlu/Aria2App#271]
![Screenshot_2023-06-19-12-06-02-82_f3595b19c7910ba157f01b460eb2e7b5](https://github.com/devgianlu/Aria2App/assets/43744334/eb894296-97a2-4dc4-be1d-70b3cafd99a9)

**Comment by devgianlu** [comment]
The permissions API changed completely in Android 13 making it very difficult to access user storage. Some major changes on how the app saves its files are required, not sure when that will be complete.

**Comment by poly000** [comment]
but in 5.9.12 with lower target sdk it's just working in good-old way

**Comment by theinsidersandrush** [comment]
Bug recreation (maybe) [Tested on  Android 13]![Screenshot_20230930-234227_Aria2App.png](https://github.com/devgianlu/Aria2App/assets/87752859/681b86c2-5d27-45fb-a259-4250069b3be9)

**Comment by devgianlu** [comment]
I have released version 5.9.14 in an attempt to fix this issue.
