### ISSUE TITLE
Impossible to go back and quit

### ISSUE THREAD

**Issue by gerroon** [devgianlu/Aria2App#29]
I like this app but one issue I find is that it is imposibble to go back and leave after a download finished

- open browser

- find a download file and share to the app

- add it and ok to start the download

- let it finish

- now use you back button to go back

It goes back to adding the link menu, then goes back and does some funcky stuff then I do not know how many million times to make it quit the app. This does not sound  like  regular behavior. I even disabled the notificiation Services

I am using it on LIneage OS 14.1 Arm

thanks

**Comment by devgianlu** [comment]
This might be related to #22
