### ISSUE TITLE
Some components are not visible in light mode

### ISSUE THREAD

**Issue by zhengqwe** [devgianlu/Aria2App#292]
left: light mode, right: dark mode
![IMG_20231013_213700](https://github.com/devgianlu/Aria2App/assets/103168200/d2d6fe72-330c-44b1-8492-1b77c5beeb97)
![IMG_20231013_213736](https://github.com/devgianlu/Aria2App/assets/103168200/cc38eaf7-8e36-4dd3-ab0f-28687cf08a66)
where the picture 2 from: click here:
![IMG_20231013_213111](https://github.com/devgianlu/Aria2App/assets/103168200/e4c898eb-fd56-473b-906b-b1fba5946734)

**Comment by devgianlu** [comment]
Thanks!
