### ISSUE TITLE
Direct download over regular web server?

### ISSUE THREAD

**Issue by gerroon** [devgianlu/Aria2App#30]
Is it possible to use Apache as a direct download provider? I looked at the direct download setup and it seems like it is running over http. I am wondering if you have a guide to set this up over Apache?

thanks

**Comment by gerroon** [comment]
thanks

**Comment by devgianlu** [comment]
I've updated the wiki: https://github.com/devgianlu/Aria2App/wiki/Setup-DirectDownload#with-apache

**Comment by gerroon** [comment]
Cool I will try it

**Comment by gerroon** [comment]
Hi 


I set this up with apache and I can put http://IP:801 in the browser and it opens the page with my aria2 downloads. I put the same url in the app, it says that there are no downloads (in the direct download path)

I did not set any user/passs and this is all in the same local network.

**Comment by devgianlu** [comment]
You can download files only from the `Files` tab, it won't display the files in the folder.

**Comment by gerroon** [comment]
I do not know what FIles tab are you talking about? I do not see any files tab at all. I have "Home", "Direct Download" 

![image](https://user-images.githubusercontent.com/8519469/50452332-198f1180-08ff-11e9-835d-85f4d13499f4.png)

**Comment by devgianlu** [comment]
If you go where all the downloads are and click `More`, you'll see that tab. You can click on a file (or press and hold on directory) to display the download icon.

**Comment by gerroon** [comment]
I see, I was not keeping my list in there once downloaded, so if the list is empty I cant redownload them I guess?

**Comment by devgianlu** [comment]
You can do that from your browser. It is too difficult for Aria2App to track which files are present in the directory and list them in the app.

**Comment by gerroon** [comment]
I see thanks for your help
