### ISSUE TITLE
FR: Download from Youtube

### ISSUE THREAD

**Issue by gerroon** [devgianlu/Aria2App#31]
Hi

I am wondering if it is possible to support downloading Youtube videos? It will be like regular download, like how Aria downloads and saves them on the server

thanks

**Comment by devgianlu** [comment]
This hasn't nothing to do with Aria2App, it is a feature that should be added to aria2. [This](https://github.com/aria2/aria2/issues/1068) could be a solution for you.

**Comment by eladkarako** [comment]
you are looking for yt-dlp  (fork of youtube-dl).
