### ISSUE TITLE
Firefox doesn't show dialog to open with Aria2App after reinstall

### ISSUE THREAD

**Issue by cacophobe** [devgianlu/Aria2App#33]
I recently reinstalled Aria2App and Firefox. Since then I am not getting the option to open-with Aria2App, like it used to show earlier. Firefox starts downloading the file immediately.

This is when I tried with .zip files. 

When I tried it with a .pdf, Firefox did show a open-with dialog, but Aria2App isn't in the list of applications shown.

Aria2App does show up in the Share menu options.

I can't figure out what changed. How do I revert to the old behavior?

**Comment by devgianlu** [comment]
I used to test it with Chrome and it works. It **doesn't work** with Firefox.

**Comment by devgianlu** [comment]
I think this might be an issue with Firefox (Opera didn't work either) as it doesn't work even after I've rolled back to the previous version. Chrome works. I think that they prefer to rely on their own download manager.

Anyway, many browsers let you long press a link to share it and there it is Aria2App.
