### ISSUE TITLE
Latest version white screen

### ISSUE THREAD

**Issue by zhengqwe** [devgianlu/Aria2App#330]
Latest version white screen. Uninstall and install again not work.
Device: Redmi Note 9 Pro, Android 12

**Comment by devgianlu** [comment]
I am unable to reproduce this behaviour. Do you have any stacktrace/log?

**Comment by Recognizer83** [comment]
having same issue

**Comment by abskmj** [comment]
Same issue. App is stuck in loading screen. Android 14.

**Comment by devgianlu** [comment]
@NielSync are you able to get a stacktrace of the exception causing the ANR?

**Comment by devgianlu** [comment]
Should be fixed in the latest release (5.9.18). Feel free to re-open if you still have problems.
