### ISSUE TITLE
DirectDownload cannot correctly handle different directory.

### ISSUE THREAD

**Issue by maple3142** [devgianlu/Aria2App#34]
My default download folder in my PC is `dir=C:/Users/Administrator/Downloads`, but I usually use another download to start some download, which set the destination to `C:/Users/Administrator/Downloads/dmhy`.
And I have a nginx server on my pc, `http://IP_OF_MYPC/Downloads/` points to `C:/Users/Administrator/Downloads` so that normal download can be correctly handled.
However, it doesn't work fine with files in `C:/Users/Administrator/Downloads/dmhy`.

**Comment by devgianlu** [comment]
What do you mean by `doesn't work`? Does it spit out any error? Check the logs.

**Comment by maple3142** [comment]
I have a file in `Downloads/dmhy` , and the path of DirectDownload is set to http://IP_OF_MYPC/Downloads.
When it try to download the file, however, the link will be http://IP_OF_MYPC/Downloads/thefile but not http://IP_OF_MYPC/Downloads/dmhy/thefile .

**Comment by devgianlu** [comment]
How do you set the path for the downloads in `dmhy`?

**Comment by maple3142** [comment]
I use other external cli tool to start the download with RPC, and it also select a different download destination.
Having an option to set a reference such as C:/Users/Administrator -> `http://IP_OF_MYPC` would be good.
Since downloaded files are not always located at default `dir`.

**Comment by devgianlu** [comment]
I can understand why this doesn't work. I'll try to come up with a solution.

**Comment by devgianlu** [comment]
@maple3142 Could you send a screenshot of the `Info` tab of one of these downloads? I'm interested on what `dir` is.

**Comment by maple3142** [comment]
![](https://i.imgur.com/UsW9TFe.png)

**Comment by devgianlu** [comment]
That should be now fixed. I'll publish a new release soon.

**Comment by maple3142** [comment]
Although it could get the correct url in latest version, but aria2app always failed to add any download.
It is possible to call external downloader to do so?

**Comment by devgianlu** [comment]
Unluckily it is not possible due to the fact that they require additional information to be passed to the client. How does it fail? Gives an error message immediately or fails afterwards?

**Comment by maple3142** [comment]
Whenever I start to download anything, there's a toast said `Failed adding the new download`.

**Comment by devgianlu** [comment]
Could you send me an email from the app?

**Comment by devgianlu** [comment]
As a temporary workaround, try stopping the app from the settings.

**Comment by maple3142** [comment]
Sorry, I found the reason why it doesn't work it that Aria2App doesn't have storage permission in app's settings page. It works when I enable it.

Besides, how I can copy or download the file through external downloaders?

**Comment by devgianlu** [comment]
I added an option in the preferences under `DirectDownload` to send the URL to another app. I'll release a new version soon.
