### ISSUE TITLE
Missing setup info

### ISSUE THREAD

**Issue by Capitalmind** [devgianlu/Aria2App#39]
Hi very keen to experiment with this app but not enough info in wiki on how to setup. Domain in particular, what settings should be used?

I'm choosing to use wifi connection and supplying my wifi SSID. as for the http address, what is expected?

**Comment by devgianlu** [comment]
This app is a client for [aria2](https://github.com/aria2/aria2), an open source download manager. aria2 can be run on Windows, Linux or even Android and in order for the app to communicate [RPC](https://aria2.github.io/manual/en/html/aria2c.html#rpc-interface) must be enabled and configured. Setting everything up needs a bit of IT knowledge and I am afraid that by writing down a guide I'll be flooded by people that can't make it work. The project [README](https://github.com/aria2/aria2/blob/master/README.rst) already provides some instructions for the setup.

Anyway, after you've downloaded aria2, run `aria2c --enable-rpc --rpc-listen-all=true --rpc-listen-port=6800 --rpc-secret=password`, then you'll need to supply the IP address of the machine along with the port (`6800` in our case) and the authentication secret (`password`).

If you need a download manager for Android, consider downloading Aria2Android.
