### ISSUE TITLE
[feature request] Add & edit url (mirrors) after starting the download process

### ISSUE THREAD

**Issue by pupyc** [devgianlu/Aria2App#41]
It would be nice if we could add more mirrors after the download has started

**Comment by devgianlu** [comment]
I don't know if this is feasible. You should try to edit the `bt-tracker` option for that specific download.

**Comment by pupyc** [comment]
I only use the app for direct downloads not bt. :v:

**Comment by devgianlu** [comment]
I don't understand what you mean then. What you mean by `mirrors`?

**Comment by pupyc** [comment]
Say I'm downloading from gdrive and paused the download for 2 days, so now simply the link is expired and will not work.

But if there is an option to add the new link to continue the download without having to add new entry

**Comment by devgianlu** [comment]
I don't think that's possible right now. Starting a new download may work, but you'll have to ask on the [aria2](https://github.com/aria2/aria2) repository.
