### ISSUE TITLE
Is it possible to add a menu to sync and add the best tracks to remote?

### ISSUE THREAD

**Issue by peerless2012** [devgianlu/Aria2App#47]
Here is the track source: [trackerslist](https://github.com/ngosang/trackerslist)

**Comment by devgianlu** [comment]
This would be a nice addition. I'll think about it and report some ideas here.

Also, what you mean with "sync"?

**Comment by peerless2012** [comment]
Set the bt tracks to remote aria2.

**Comment by devgianlu** [comment]
I've added this feature. You can know add the best trackers from the `bt-tracker` option dialog or automatically by enabling the feature in the preferences.

**Comment by peerless2012** [comment]
> I've added this feature. You can know add the best trackers from the `bt-tracker` option dialog or automatically by enabling the feature in the preferences.

But i can't find the option or dialog on 4.4.2

**Comment by devgianlu** [comment]
The new version is yet to come out.
