### ISSUE TITLE
Is it possible to have only 1 notification when using the in-app downloader?

### ISSUE THREAD

**Issue by Pentaphon** [devgianlu/Aria2App#58]
For some reason, the aria2c service notification cannot be closed like the other notification, even though aria2app is behaving as a single application. Can we only have one notification running so that we can easily close it when we don't need to use aria2app anymore? 

![Screenshot_20190517-021948](https://user-images.githubusercontent.com/49374058/57917901-8e310100-784a-11e9-87fd-3eef815ea417.png)

Is there any chance you can merge both notifications into 1 single notification when using the in-app downloader? It seems unnecessary to have 2 notifications always running, especially when only 1 of them can be closed with a "stop service" button. 

I'm running the latest 5.1 version.

**Comment by devgianlu** [comment]
There must be an issue with the stop button (it should be visible), I'll be investigating this first. 

I may also get around to merging the two notifications.

**Comment by devgianlu** [comment]
This is not possible because of the Service lifecycle.
