### ISSUE TITLE
[Feature Request] WebView Icon

### ISSUE THREAD

**Issue by hjyoung1** [devgianlu/Aria2App#59]
Thank you so much for your work.
I want to request 2 Enhancements for webview. Please add them if you think there're reasonable. 
1 :- currently tapping back button closes webview, but it will be better if it should go back to previous page (not close browser) 
2 :- add setting to add webview browser icon into launcher (like adm do *ss*) this makes adding files much easier. 
![Screenshot_20190519-010440](https://user-images.githubusercontent.com/45882061/57974217-56ed5c00-79d2-11e9-9161-b635e2a45850.png)

**Comment by devgianlu** [comment]
These are actually good suggestions. I'll be working on that.
