### ISSUE TITLE
In app downloader doesn't start automatically when sharing URL

### ISSUE THREAD

**Issue by opusforlife** [devgianlu/Aria2App#61]
If you open the app from the app drawer, and there is no other profile listed, the in app downloader starts automatically and the app opens to the downloads screen. This is expected behaviour.

However, if you try to start a download directly from the browser and select the app, it opens to the profile selection screen, with the message "Connecting", the loading circle glitching indefinitely, while a toast says "Failed connecting!". It stays like that until you back out of the app.

If you do have another profile, then you get the option of selecting one. Selecting the in app downloader shows the toast saying it failed to connect again, but it starts the service in the background. Selecting it again finally takes you to the Add URL screen.
If the Aria2Android service isn't running in the background, then selecting the Aria2Android profile gives the toast saying it failed to connect, too. Tapping it again makes no difference. You need to ensure it is running beforehand.

This means whenever you want to download something from the browser with the in app downloader and have no other profile, you need the extra step to open the app from the app drawer, hence starting the in app downloader, then switch back to the browser and start the download.
The same applies to the Aria2Android profile. You need to start it before you initiate the download.

This problem appeared with the inclusion of the in app downloader. But earlier behavior was a little complicated too. You initiate a download with Aria2App. It gives the Webview message. Reject it. It then gives a message saying the local profile isn't running and if you want to start it. You accept. It opens Aria2Android. You start it. Go back. Aria2App doesn't open the Add URL screen. Instead it opens the downloads screen. Go back. Initiate the download from the browser again. Finally, you get the Add URL screen.

Expected behaviour:
With no other profile except the in app downloader, any download initiated from the browser should take you directly to the Add URL screen, with the downloader service starting in the background.

**Comment by devgianlu** [comment]
Should be fixed now. Also note that using Aria2Android on the save device as Aria2App is not officially supported anymore, using the in-app downloader is the recommended way. Thank you for your feedback.
