### ISSUE TITLE
Webview signin issue 

### ISSUE THREAD

**Issue by hjyoung1** [devgianlu/Aria2App#62]
I'm not able to signin using webview on google drive to download files.
Link :- https://drive.google.com/a/apps.losrios.edu/file/d/1X_C0zzk-LEXg9vVhahtyFGs3-rqMtNUI/view?usp=drivesdk 
This my university account, Link is not public so i have to signin 1st to access/download my files. 
But whenever i try to access this i get this. 
![Screenshot_20190522-210533](https://user-images.githubusercontent.com/45882061/58192600-c28b3e00-7cde-11e9-9f30-631c819cf210.png)

Another link where I'm having problems. 
Link 2 :- https://drive.google.com/file/d/1gh2CXrMbB5EtEKcgfm61omrDmIeNCSJR/view?usp=drivesdk
This is from my personal account, again link is not public so i have to signin before accessing it. But signin page not working. 
Tapping on next button does nothing. 
![Screenshot_20190522-210835](https://user-images.githubusercontent.com/45882061/58192916-77bdf600-7cdf-11e9-846c-ad05a6876908.png)

I also have two enhancement request for webview. 
1 :- Add loading progress bar. 
2 :- Allow Search. In current build I'm not able to search it shows only blank white screen.

**Comment by devgianlu** [comment]
Second issue is probably due to this: https://stackoverflow.com/a/51167288/5446197

Still investigating the first one.

**Comment by hjyoung1** [comment]
![Screenshot_20190523-011153](https://user-images.githubusercontent.com/45882061/58203571-05a5db00-7cf8-11e9-9fd6-cd251ee0de03.png)
Like this if no url is entered then visit should search on Google.

**Comment by devgianlu** [comment]
While the first issue seems to fixed, there are some major issues with the second one and the WebView in general. 

The page isn't often allowed to load content:
```
I/chromium: [INFO:CONSOLE(0)] "Refused to display 'https://accounts.youtube.com/accounts/CheckConnection?pmpo=https%3A%2F%2Faccounts.google.com&v=316880018&timestamp=1558618813147' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors https://accounts.google.com".", source: about:blank (0)
I/chromium: [INFO:CONSOLE(0)] "Failed to load https://www.google.com/drive/: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://drive.google.com' is therefore not allowed access.", source: https://drive.google.com/file/d/1Axqnhgtnw1bCDdlIxVC7ALRWa1tk6YWx/view (0)
```

Also the fact that `http://google.it` doesn't load images, but `http://www.google.it` does is a bit strange.

Not quite sure what to do now. These issues happen quite a lot and I don't think there's a solution. For that reason I'm not implementing any search functionality neither the loading bar.

**Comment by devgianlu** [comment]
I have recently discovered the existence of the GeckoView (developed by Mozilla) which is much better than the WebView. However the engine adds a 100mb to app size which is not something I can deal with it. I am trying to understand whether it is possible to utilize the engine from Aria2App if Firefox is installed on the device.

**Comment by devgianlu** [comment]
@hjyoung1 I've just release [v5.6.1](https://github.com/devgianlu/Aria2App/releases/tag/v5.6.1) with some improvements to the WebView. Does it fix this issue?
