### ISSUE TITLE
why cannot change the conf ?

### ISSUE THREAD

**Issue by powersee** [devgianlu/Aria2App#64]
I use the in-APP downloader in the aria2APP.

I want to change the config ,like the rpc listen-port to 6800. so i change it and apply.

But when i restart aria2APP , i found it didn't work...Just like i didn't change.

**Comment by devgianlu** [comment]
The option is overridden by a default value hardcoded in the app. May I ask why you need to change that?

**Comment by powersee** [comment]
I also download your another app : aria2Android , and it's listen port is 6800 ,so i want to change ……

But now needn't , i know how to change the conf in aria2APP , just need to hold on the  **in-APP downloader** ,then it just like in the aria2APP . All in All ,thank you very much.
