### ISSUE TITLE
metalink4 file

### ISSUE THREAD

**Issue by marcellmars** [devgianlu/Aria2App#65]
if i add uri to aria2app https://books.memoryoftheworld.org/search/authors/Chris%20Kraus?dl=meta4 aria2app will happily download all of the files with the directory structure as metalink file states.

if i do it via browser and download the file aria2app will not find that file as mime type application/metalink4+xml so it doesn't make it possible to be added.

if i try through file browser to share or open with aria2app it complains it is invalid file.

i don't have much experience in handling the file/mime types on android. i would like if i can make my server api prepare better the file for android download.

the same file if downloaded on linux would work just fine with aria2c -c that_file.meta4

**Comment by devgianlu** [comment]
Currently, Aria2App isn't able to recognize a meta4 file when sharing it from the browser, it'll see the link as a standard file to download.

I have to investigate why it is not able to load it by sharing the file.

By the way, you server response to download the file looks like this:
```
HTTP/1.1 200 OK
Server: nginx/1.14.0 (Ubuntu)
Date: Fri, 07 Jun 2019 13:31:57 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Content-Disposition: Attachment; filename="search_authors_chris kraus.META4"
Access-Control-Allow-Origin: *
```

But you should really set `Content-Type` to a correct value like `application/metalink4+xml`.

**Comment by marcellmars** [comment]
i asked at sanic forum about the content-type header around the same time like here ;)

the question if anyone will follow up on this is: https://community.sanicframework.org/t/content-type-header-for-file-stream/320

eventually i will get content-type fixed too. thank you for your work @devgianlu ...
