### ISSUE TITLE
`-max-tries` option does not appear to work

### ISSUE THREAD

**Issue by Prajjwal** [devgianlu/Aria2App#67]
I'm using the app, with aria2 v1.34 release off Github.

Setting the `-max-tries` option does not appear to work, downloads stop whenever connection is lost (which is a lot when on mobile internet).

Relevant error string: `Error #1: No URI available.`.

I found a suspicious `max-tries,` option in https://github.com/devgianlu/Aria2App/blob/7e129a2e43d21385b94caf630abe449f1b67cf9d/app/src/main/assets/options.json, which might be the cause of the problem, but I'm not sure.

**Comment by devgianlu** [comment]
Where are you setting this option? The correct name for usage in Aria2App is `max-tries`.

**Comment by Prajjwal** [comment]
I'm not, I'm setting `max-tries`. I just noticed that there's also `max-tries,` and included that in case that has something to do with it.

**Comment by devgianlu** [comment]
I've looked a bit into this and it's totally not an Aria2App issue, please refer to https://github.com/aria2/aria2/issues
