### ISSUE TITLE
Rights on android oreo

### ISSUE THREAD

**Issue by cmarxmeier** [devgianlu/Aria2App#70]
for wiki: 
to overcome limits when using external SD-Card as default download storage for aria2app in oreo:
Magisk +Magisk Manager + Module "ExSDCard AccessEnable" comes handy.
It mounts SD-Card read/writable to /mnt/media_rw/<ID> with permission to use for everyone-user. 
This way, oreo does not complain about missing rights to use path that links to external SD-Card.

**Comment by devgianlu** [comment]
https://github.com/devgianlu/Aria2App/wiki/Issues-with-SD-card

**Comment by cmarxmeier** [comment]
should be enough guidance for people with basic knowledge  - complete howto would ask for masses of rooting device questions. Maybe link to https://www.xda-developers.com/what-is-magisk/ for magisk term is helpful.
