### ISSUE TITLE
Add support for "self-signed" certificates for DirectDownload

### ISSUE THREAD

**Issue by devgianlu** [devgianlu/Aria2App#8]

**Comment by devgianlu** [comment]
Needs testing.

**Comment by genofire** [comment]
It would also be nice at "normal" host.

**Comment by devgianlu** [comment]
@genofire What do you mean?

**Comment by genofire** [comment]
I am not able to connect to a aria2c rpc daemon which used a self-signed cert

**Comment by devgianlu** [comment]
This feature is already available. You need to provide your certificate to the app so that it can verify the host.

**Comment by genofire** [comment]
The self-signed certificate changed often ...

**Comment by devgianlu** [comment]
There's no way to use TLS then, the client needs to know the certificate if it isn't trusted by the system, which won't be as it's self-signed. Please consider using https://letsencrypt.org/

**Comment by genofire** [comment]
It is no public ip-address, i just want to be sure that no other wifi user could read my token.
(the changing happens on every restart ... )

**Comment by devgianlu** [comment]
Please read [How does SSL/TLS work](https://security.stackexchange.com/questions/20803/how-does-ssl-tls-work).

**Comment by genofire** [comment]
sorry
