### ISSUE TITLE
Feature request: Default global options

### ISSUE THREAD

**Issue by leotaku** [devgianlu/Aria2App#80]
I think having the ability to set default values through the Global Options and Quick Options menus would be a great addition to Aria2App.

My usecase for this would be setting the port numbers that aria2c uses, as my VPN provider allows setting up some ports that can be forwarded. But I would imagine there are other scenarios where this feature would be useful.

Thank you for your great work!

**Comment by devgianlu** [comment]
What do you mean by defaults?

**Comment by leotaku** [comment]
So what happens currently with the global settings (at least for me) is that they are not stored between app restarts. If I want a specific setting I have to edit it in the global/quick menu and press apply every time I restart the app.

By setting a value as default it would be stored and automatically applied (when not overridden by a more specific setting). Does what I would like to achieve make sense now?

**Comment by devgianlu** [comment]
Sorry, I hadn't understand that you are using the In-App downloader. This is definitely an interesting and useful feature, I'll implement it.

**Comment by devgianlu** [comment]
When changing global options, the changes will be permanent and exported to the "Custom options" section of the In-App Downloader.

**Comment by leotaku** [comment]
Thank you very much!

Could you maybe clarify what you mean by 
'exported to the "Custom options"'?

**Comment by devgianlu** [comment]
> Could you maybe clarify what you mean by 'exported to the "Custom options"'?

If you tap and old on the In-App Downloader profile, you'll see a configuration screen and a button called "Custom options". All the global options that you change will end up there.

**Comment by PacoBell** [comment]
Did you remove this feature? I don't see a "Custom options" button.
