### ISSUE TITLE
Add "open with" feature

### ISSUE THREAD

**Issue by proneon267** [devgianlu/Aria2App#82]
Please add "open with" feature as without it, the only way download a file is to share download link or add the URL manually. Open with feature will enable users to directly open aria2app to download files.

**Comment by devgianlu** [comment]
An "open with" feature is already available. 
I suppose you're having issues with it. Could you elaborate?

**Comment by proneon267** [comment]
Whenever I click any download link, it just straight up starts downloading in the internal-browser downloader. I am using brave browser and have also tried with Google chrome but still no difference.

**Comment by devgianlu** [comment]
Some browsers will refuse to open the picker dialog. A workaround is to tap and hold and then use the share link option.
