### ISSUE TITLE
 Specify minimum SSL/TLS on version 1.35.0

### ISSUE THREAD

**Issue by lindroidux** [devgianlu/Aria2App#86]
```
1574604744989|2.3.0-foss|INFO
 --min-tls-version=VERSION    Specify minimum SSL/TLS version to enable.

1574604744994|2.3.0-foss|INFO
Terminated with exit code 28.

1574604744994|2.3.0-foss|INFO
Terminated with exit code 28.

1574604744994|2.3.0-foss|INFO
Terminated with exit code 28.

1574604752705|2.3.0-foss|INFO
(event: aria2_off, bundle: Bundle[{session_duration=8308}])
```

**Comment by devgianlu** [comment]
Which other options did you specify?

**Comment by lindroidux** [comment]
1574604744940|2.3.0-foss|INFO
Started: /data/user/0/com.gianlu.aria2android/files/env/aria2c --auto-save-interval=60 --disk-cache=16777216 --bt-tracker-interval=0 --force-save=false --enable-rpc=true --bt-stop-timeout=0 --ftp-reuse-connection=true --rpc-listen-all=true --dry-run=false --http-auth-challenge=false --daemon=false --piece-length=1048576 --seed-ratio=1.0 --dht-file-path=/data/.cache/aria2/dht.dat --save-not-found=true --optimize-concurrent-downloads=false --quiet=false --min-split-size=1M --bt-seed-unverified=false --dht-file-path6=/data/.cache/aria2/dht6.dat --metalink-preferred-protocol=none --log-level=debug --keep-unfinished-download-result=true --metalink-enable-unique-protocol=true --http-accept-gzip=false --no-file-allocation-limit=5242880 --allow-overwrite=false --disable-ipv6=false --pause-metadata=false --stream-piece-selector=default --show-console-readout=true --bt-detach-seed-only=false --show-files=false --max-concurrent-downloads=5 --bt-tracker-timeout=60 --console-log-level=notice --content-disposition-default-utf8=false --bt-metadata-only=false --file-allocation=prealloc --peer-agent=aria2/1.35.0 --user-agent=aria2 --dht-message-timeout=10 --use-head=false --conf-path=/storage/emulated/0/aria2c/.config/aria2.conf --human-readable=true --max-connection-per-server=3 --parameterized-uri=false --bt-save-metadata=false --enable-dht6=false --bt-require-crypto=false --remote-time=false --bt-min-crypto-level=plain --enable-http-pipelining=false --rpc-secure=false --continue=false --bt-load-saved-metadata=false --http-no-cache=false --enable-mmap=false --input-file=/data/user/0/com.gianlu.aria2android/files/session --max-overall-download-limit=0 --bt-enable-hook-after-hash-check=true --bt-force-encryption=false --lowest-speed-limit=0 --reuse-uri=true --dir=/storage/emulated/0/1aria2app --max-download-result=1000 --rpc-listen-port=6800 --bt-max-open-files=100 --always-resume=true --allow-piece-length-change=false --bt-tracker-connect-timeout=60 --timeout=60 --max-upload-limit=0 --remove-control-file=false --netrc-path=/data/.netrc --no-conf=false --check-certificate=false --max-tries=999 --check-integrity=false --enable-color=false --socket-recv-buffer-size=0 --conditional-get=false --bt-max-peers=55 --bt-request-peer-speed-limit=51200 --rpc-max-request-size=2097152 --rpc-secret=aria2 --peer-id-prefix=A2-1-35-0- --server-stat-timeout=86400 --save-session-interval=10 --max-download-limit=0 --follow-metalink=true --dscp=0 --ftp-type=binary --no-netrc=false --rpc-save-upload-metadata=true --split=5 --max-resume-failure-tries=0 --realtime-chunk-checksum=true --deferred-input=false --summary-interval=60 --auto-file-renaming=true --truncate-console-readout=true --max-mmap-limit=9223372036854775807 --bt-hash-check-seed=true --retry-wait=5 --dht-listen-port=6881-6999 --connect-timeout=60 --follow-torrent=true --enable-peer-exchange=true --stop=0 --max-file-not-found=0 --save-session=/data/user/0/com.gianlu.aria2android/files/session --stderr=false --rpc-allow-origin-all=false --event-poll=epoll --proxy-method=get --hash-check-only=false --enable-dht=true --bt-remove-unselected-file=false --ftp-pasv=true --download-result=default --async-dns=true --uri-selector=feedback --listen-port=6881-6999 --enable-http-keep-alive=true --max-overall-upload-limit=0 --bt-enable-lpd=false

**Comment by lindroidux** [comment]
https://stackoverflow.com/questions/28943660/how-to-enable-tls-1-2-support-in-an-android-application-running-on-android-4-1

Will it be helpful?

**Comment by devgianlu** [comment]
This has nothing do to with the app. Error 28 is returned `f bad/unrecognized option was given or unexpected option argument was given.`: you may want to reviews all these options first.

**Comment by lindroidux** [comment]
Yeah, I removed all custom options & it is running fine.
Will try each option, one by one.
Thank u for the great app.
