### ISSUE TITLE
F-Droid build of 5.6.0 is failing

### ISSUE THREAD

**Issue by opusforlife2** [devgianlu/Aria2App#90]
Probably needs some modification to accommodate the change involving the inclusion of the binary. The latest version on F-Droid is 5.4.5, without the aria2c binary.

**Comment by devgianlu** [comment]
https://gitlab.com/fdroid/fdroiddata/issues/1878

**Comment by opusforlife2** [comment]
So... what now? Are you gonna try letting F-Droid build the binary?

**Comment by devgianlu** [comment]
They stopped responding so I don't really know what I could do. I can't even create a PR because I don't know how the build server works.

**Comment by opusforlife2** [comment]
Nice to see the situation resolved. :) You work very fast, man.

**Comment by devgianlu** [comment]
Thanks, now I am just waiting to see the app being built [here](https://f-droid.org/wiki/index.php?title=Special:RecentChanges&days=7&from=&hidebots=0&hideanons=1&hideliu=1&limit=500) and then I'll create a PR for Aria2App.

**Comment by opusforlife2** [comment]
I know. :) I'm following every step of the process.

**Comment by mimi89999** [comment]
You could see how I was building LibreSignal libs.

**Comment by devgianlu** [comment]
The build has been already setup, we are waiting for it to complete on the build server.

**Comment by devgianlu** [comment]
Hooray! Build succeeded: https://f-droid.org/wiki/page/com.gianlu.aria2android/lastbuild_65

**Comment by Qyrln** [comment]
more than a month and still hasn't been updated yet in fdroid .

**Comment by devgianlu** [comment]
@Qyrln I though the build would work because it worked on Aria2Android and it should have done, if it wans't for some strange network errors that seem to hunt the entire platform. I'll try to get in contact with the maintainers.

https://f-droid.org/wiki/page/com.gianlu.aria2app/lastbuild_205

**Comment by opusforlife2** [comment]
Something has been done just a few hours ago to the YAML. Let's see if that works.

https://gitlab.com/fdroid/fdroiddata/-/commit/7bebabc336d55f10026e2d6533a6bd72f1dffca7#fd2454fe94a25630ca951a101e8c723e0b1adb6d

**Comment by devgianlu** [comment]
Finally working!
