### ISSUE TITLE
Schedule download feature

### ISSUE THREAD

**Issue by devgianlu** [devgianlu/Aria2App#91]
Add the possibility to schedule to start a download in the future. I am not sure whether this belongs here, could be an aria2 feature.

**Comment by hostkit** [comment]
> Add the possibility to schedule to start a download in the future. I am not sure whether this belongs here, could be an aria2 feature.

In pc/router we can using curl, i dont know if on Android. Maybe menu can do it

**Comment by devgianlu** [comment]
Moved to https://github.com/aria2/aria2/issues/1562, will take action based on what happens there.
