### ISSUE TITLE
[Feature Request] Skip link addition screen when download link is shared

### ISSUE THREAD

**Issue by opusforlife2** [devgianlu/Aria2App#93]
When the link is shared, after the webview prompt, we get the screen where we can add multiple links to the same resource. This is another feature I have not needed so far.

Could there be a toggle in settings to disable this screen and go straight to downloading?

If I ever encounter a download where I need to add multiple links, I could do it by using the Floating Action Button from within the app.

**Comment by devgianlu** [comment]
The problem with skipping such screen is that you won't be able to change the download options. I don't think having to confirm the download is a big hassle, it's also a "safety feature".

**Comment by opusforlife2** [comment]
Good point.

Then how about this? If a link is shared from another app, it should bypass the "Add URI" dialog box and be added to the URI list by default. If a wrong link has been entered, there is already a convenient trash button to remove it. This removes one tap out of two before the download begins.

**Comment by opusforlife2** [comment]
@devgianlu Pinging you because I don't know if Github stops sending notifications if the issue is closed.

**Comment by opusforlife2** [comment]
Awesome! Thanks!
