### ISSUE TITLE
[Request] Ability to export and import aria2 input file / session file  

### ISSUE THREAD

**Issue by lesca** [devgianlu/Aria2App#95]
Hi Devgianlu,

I am looking for the feature to import / export aria2 input file, which is also known as session file.
[https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-i](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-i)
[https://aria2.github.io/manual/en/html/aria2c.html#input-file](https://aria2.github.io/manual/en/html/aria2c.html#input-file)

If this is possible, we can easily use the session file to migrate the download status between phones and PC.

Can this make sense? Thanks!

**Comment by devgianlu** [comment]
I can add this feature to export the session file, but I don't really understand how you'll be able to migrate the download status without also moving the downloaded files.
