### ISSUE TITLE
[Feature request] Restore grey dark theme as an option

### ISSUE THREAD

**Issue by opusforlife2** [devgianlu/Aria2App#98]
Coming from 5.4.5, the new dark theme has too high a contrast. It would be good to have 3 options like other apps have: light, dark and black theme.

Also, is it possible to have another colour instead of orange? A cool (as opposed to warm, not uncool) colour like blue or green.

**Comment by devgianlu** [comment]
The change you've seen is probably due to the migration to the newest Material Design guidelines. I am not very good at creating themes and UI stuff in general. 

If someone wants to start working on this, it is very appreciated!
