### ISSUE TITLE
Could not build project on AndroidStudio

### ISSUE THREAD

**Issue by Naciim** [devgianlu/Aria2App#99]
Hello
I realy love your app, i want add some features, but in AndroidStudio, i have got somme erreur, when i import the projet.
ERROR: Unable to resolve dependency for ':app@fossDebug/compileClasspath': Could not resolve project :CommonUtils.
ERROR: Unable to resolve dependency for ':app@fossDebugUnitTest/compileClasspath': Could not resolve project :aria2lib.
Do you have somme documentation to setup the projet ?

AndroidStudio 3.6.3

Thks

**Comment by devgianlu** [comment]
You should clone the submodules too.

**Comment by Naciim** [comment]
Haha, Thank you very match :)
